# Generated by Django 5.1.2 on 2024-10-17 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logotipo', models.URLField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('puntos_contribuidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('posicion_final', models.IntegerField(default=0)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('tiempo_jugado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('clave_de_acceso', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('puntos_contribuidos', models.IntegerField(default=0)),
                ('tiempo_jugado', models.FloatField(default=0.0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.equipo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.participante')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='equipos',
            field=models.ManyToManyField(through='torneo.ParticipanteEquipo', to='torneo.equipo'),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('id_consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.consola')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_torneo', to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='TorneoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('fecha_participacion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('pendiente', 'Pendiente')], default='activo', max_length=50)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.juego')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='torneos',
            field=models.ManyToManyField(through='torneo.TorneoJuego', to='torneo.torneo'),
        ),
        migrations.CreateModel(
            name='TorneoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('posicion_final', models.IntegerField(default=0)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.participante')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='participantes',
            field=models.ManyToManyField(through='torneo.TorneoParticipante', to='torneo.participante'),
        ),
        migrations.CreateModel(
            name='PerfilDeJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('avatar', models.URLField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneo.usuario'),
        ),
        migrations.CreateModel(
            name='Espectador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_interés', models.IntegerField(default=0)),
                ('comentarios', models.TextField()),
                ('frecuencia_visitas', models.IntegerField()),
                ('suscripcion', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('torneos_ganados', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torneo.usuario')),
            ],
        ),
    ]
