# Generated by Django 5.1.2 on 2024-10-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espectador',
            old_name='nivel_interés',
            new_name='nivel_interes',
        ),
    ]
