# Generated by Django 5.1.2 on 2024-10-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_rename_nivel_interés_espectador_nivel_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='torneo.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
