# Generated by Django 5.1.2 on 2024-10-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_alter_clasificacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='torneo.usuario'),
        ),
    ]
