# Generated by Django 5.1.2 on 2024-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_alter_clasificacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='participantes',
            field=models.ManyToManyField(related_name='participante_torneo', through='torneo.TorneoParticipante', to='torneo.participante'),
        ),
    ]
