# Generated by Django 5.1.2 on 2024-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_alter_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
